# -*- coding: utf-8 -*-
"""Text Generation : GPT-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYRAcHHzqtP8N47OM-jsfzv4oQkLzK_M
"""

!pip install transformers

"""# *Starting with GPT-2 a transformer Model developed by OpenAi.*"""

from transformers import GPT2Tokenizer, GPT2LMHeadModel

"""## **1. Convert the sentences into the tokens**"""

tokenizer = GPT2Tokenizer.from_pretrained('gpt2-large')

model = GPT2LMHeadModel.from_pretrained('gpt2-large', pad_token_id=tokenizer.eos_token_id)

tokenizer.eos_token_id

tokenizer.decode(tokenizer.eos_token_id)

sentence = 'I love reading novels'
numeric_ids = tokenizer.encode(sentence, return_tensors='pt')

numeric_ids

tokenizer.decode(numeric_ids[0][3])

"""# **2. Convert the text given the sentence**"""

result = model.generate(numeric_ids, max_length = 100, num_beams=5, no_repeat_ngram_size=2, early_stopping=True)

result

generated_text = tokenizer.decode(result[0], skip_special_tokens=True)
print(generated_text)

"""# **Thank You**"""